# Generated by Django 4.1 on 2022-08-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
